# -*- coding: utf-8 -*-
# x= ('34', '67', '55', '33', '12', '98')
# y=list(x)
# x=tuple(y)
# print(x)
# print(y)
values=str(input("nhap vao gia tri: "))
l=values.split(",")
t=tuple(l)
print (l)
print (t)